CREATE TABLE `LEARNING_ANALYTICS`.`CATEGORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `PRIORITY` tinyint(4) NOT NULL,
  `DEADLINE` datetime NOT NULL,
  `SETUP` tinyint(4) NOT NULL,
  `IS_ACTIVE` tinyint(4) NOT NULL,
  `IS_MASTER_LIST` tinyint(4) DEFAULT NULL,
  `IS_MASTER_LIST_REQUIRED` tinyint(4) DEFAULT NULL,
  `IS_APPROVAL_REQUIRED` tinyint(4) DEFAULT NULL,
  `DEADLINE_CHECK` tinyint(4) DEFAULT NULL,
  `ACTION_FOR_DUPLICATES_BEFORE_DEADLINE` tinyint(4) DEFAULT NULL,
  `PROGRESS` float DEFAULT NULL,
  `ISSUE_COUNT` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`ENTITY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_CODE` varchar(50) NOT NULL,
  `ENTITY_NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `ADDRESS` varchar(250) DEFAULT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `UPDATED_BY` int(11) NOT NULL,
  `UPDATED_DATE` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ENTITY_NAME_IDX` (`ENTITY_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`ENTITY_TEMPLATE` (
  `TEMPLATE_ID` int(11) NOT NULL,
  `ENTITY_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  PRIMARY KEY (`ENTITY_ID`,`TEMPLATE_ID`),
  KEY `ENTITY_ID_IDX` (`ENTITY_ID`),
  KEY `TEMPLATE_ID_IDX` (`TEMPLATE_ID`),
  CONSTRAINT `ENTITY_TEMPLATE_TEMPLATE_ID` FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `TEMPLATE` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`IMAGE` (
  `USER_ID` int(11) NOT NULL,
  `IMAGE` longblob,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `UPDATED_BY` int(11) NOT NULL,
  `UPDATED_DATE` datetime NOT NULL,
  PRIMARY KEY (`USER_ID`),
  CONSTRAINT `FK_USER_IMAGE` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`LOGIN` (
  `USER_ID` int(11) NOT NULL,
  `LOGIN_ID` varchar(50) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `ACTIVE` tinyint(4) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `INACTIVE_DATE` datetime DEFAULT NULL,
  `UNSUCCESSFUL_LOGIN_ATTEMPTS` tinyint(4) NOT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `USER_LOGIN_ID_IDX` (`LOGIN_ID`),
  CONSTRAINT `FK_USER_LOGIN` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`MODULE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MODULE_NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `MODULE_NAME_IDX` (`MODULE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`NOTIFICATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOTIFICATION` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(250) NOT NULL,
  `PRIORITY` tinyint(4) NOT NULL,
  `SCHEDULE` tinyint(4) NOT NULL,
  `IS_ENABLED` tinyint(4) NOT NULL,
  `TRIGGER_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `UPDATED_BY` int(11) NOT NULL,
  `UPDATED_DATE` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `TRIGGER_ID_IDX` (`TRIGGER_ID`),
  CONSTRAINT `NOTIFICATION_TRIGGER_ID` FOREIGN KEY (`TRIGGER_ID`) REFERENCES `TRIGGER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TEST`.`PRIVILEGE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `ACTIVE` tinyint(4) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `PREVILEGE_NAME_IDX` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8;

INSERT INTO TEST.PRIVILEGE
(ID, NAME, DESCRIPTION, PARENT_ID, ACTIVE)
VALUES(0, 'privilege1', 'privilege1', 0, 1);

SELECT * FROM TEST.PRIVILEGE;

CREATE TABLE `LEARNING_ANALYTICS`.`ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(80) NOT NULL,
  `STATUS` tinyint(4) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `UPDATED_BY` int(11) NOT NULL,
  `UPDATED_DATE` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ROLE_NAME_IDX` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`ROLE_PRIVILEGE` (
  `PRIVILEGE_ID` int(11) NOT NULL,
  `ROLE_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  PRIMARY KEY (`PRIVILEGE_ID`,`ROLE_ID`),
  KEY `PREVILEGE_ID_IDX` (`PRIVILEGE_ID`),
  KEY `ROLE_ID_IDX` (`ROLE_ID`),
  CONSTRAINT `ROLE_PRIVILEGE_PREVILEGE_ID` FOREIGN KEY (`PRIVILEGE_ID`) REFERENCES `PRIVILEGE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `ROLE_PRIVILEGE_ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`SECURITY_POLICY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CHANGE_PASSWORD_INTERVAL` int(11) NOT NULL,
  `PASSWORD_EXPIRY_NOTIFICATION` int(11) NOT NULL,
  `LOCK_USER_ATTEMPTS` int(11) NOT NULL,
  `REENABLE_TIMEOUT` int(11) NOT NULL,
  `PASSWORD_MIN_LENGTH` int(11) NOT NULL,
  `PASSWORD_MIN_CHARS` int(11) NOT NULL,
  `PASSWORD_MIN_UPPER_CHARS` int(11) NOT NULL,
  `PASSWORD_MIN_DIGITS` int(11) NOT NULL,
  `PASSWORD_MIN_SPECIAL_CHARS` int(11) NOT NULL,
  `PREVENT_OLD_PASSWORD_REUSE` tinyint(1) NOT NULL,
  `PASSWORD_NOT_MATCH_PREVIOUS` int(11) NOT NULL,
  `PASSWORD_RESET_LINK_EXPIRATION` int(11) NOT NULL,
  `INACTIVITY_TIMEOUT` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `UPDATED_BY` int(11) NOT NULL,
  `UPDATED_DATE` datetime NOT NULL,
  `LOCK_AFTER_ATTEMPTS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`SUB_CATEGORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` int(11) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `ISSUE_COUNT` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CATEGORY_ID_IDX` (`CATEGORY_ID`),
  CONSTRAINT `SUB_CATEGORY_CATEGORY_ID` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`TEMPLATE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FEED_ID` varchar(50) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `SUB_CATEGORY_ID` int(11) NOT NULL,
  `SAMPLE_FILE_LOCATION` varchar(100) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `IS_ACTIVE` tinyint(4) DEFAULT NULL,
  `ISSUE_COUNT` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `SUB_CATEGORY_ID_IDX` (`SUB_CATEGORY_ID`),
  CONSTRAINT `TEMPLATE_SUB_CATEGORY_ID` FOREIGN KEY (`SUB_CATEGORY_ID`) REFERENCES `SUB_CATEGORY` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`TRIGGER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRIGGER_NAME` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `MODULE_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`,`MODULE_ID`),
  KEY `TRIGGER_NAME_IDX` (`TRIGGER_NAME`),
  KEY `TRIGGER_MODULE_ID` (`MODULE_ID`),
  CONSTRAINT `TRIGGER_MODULE_ID` FOREIGN KEY (`MODULE_ID`) REFERENCES `MODULE` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `PHONE` varchar(20) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `TITLE` varchar(50) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`USER_ENTITY` (
  `USER_ID` int(11) NOT NULL,
  `ENTITY_ID` int(11) NOT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `CREATED_BY` int(11) NOT NULL,
  PRIMARY KEY (`USER_ID`,`ENTITY_ID`),
  KEY `USER_ID_IDX` (`USER_ID`),
  KEY `ENTITY_ID_IDX` (`ENTITY_ID`),
  CONSTRAINT `USER_ENTITY_ID` FOREIGN KEY (`ENTITY_ID`) REFERENCES `ENTITY` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `USER_ENTITY_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`USER_NOTIFICATION` (
  `NOTIFICATION_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `IS_READ` tinyint(1) DEFAULT NULL,
  `CREATED_DATE` datetime NOT NULL,
  KEY `USER_NOTIFICATION_USER_ID_IDX` (`USER_ID`),
  KEY `USER_NOTIFICATION_NOTIFICATION_ID_IDX` (`NOTIFICATION_ID`),
  CONSTRAINT `USER_NOTIFICATION_NOTIFICATION_ID` FOREIGN KEY (`NOTIFICATION_ID`) REFERENCES `NOTIFICATION` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `USER_NOTIFICATION_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LEARNING_ANALYTICS`.`USER_OLD_PASSWORDS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `EXPIRED_DATE` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_OLD_PASSWORD_ID_IDX` (`USER_ID`),
  CONSTRAINT `FK_USER_OLD_PASSWORD` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `LEARNING_ANALYTICS`.`USER_ROLE` (
  `ROLE_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  PRIMARY KEY (`ROLE_ID`,`USER_ID`),
  KEY `ROLE_ID_IDX` (`ROLE_ID`),
  KEY `USER_ID_IDX` (`USER_ID`),
  CONSTRAINT `USER_ROLE_ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `USER_ROLE_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
